### ISSUE TITLE
Player 2 keyboard control not working in RetroPie 3.0

### ISSUE THREAD

**Issue by RigacciOrg** [RetroPie/pifba#1]
PiFBA is the default Neo-Geo emulator in RetroPie 3.0 SD card image for the Raspberry Pi 2.

Configuring player 2 keboard keys in /opt/retropie/configs/fba/fba2x.cfg does not work: keys are all non functional. Tested with USB keyboard or with a Mini-PAC interface.

Replacing the fba2x binary with another one (found here: https://github.com/ian57/Raspicade-configuration-files/blob/master/pifba/fba2x) solves the problem.

**Comment by meleu** [comment]
This part of gp2xsdk.cpp (lines [259](https://github.com/RetroPie/pifba/blob/master/rpi/gp2xsdk.cpp#L259)-286) determines how many valid joysticks are plugged to the system and store this number in the joyCount variable:

```
    //We handle up to four joysticks
    if(SDL_NumJoysticks())
    {
        int i;
        SDL_JoystickEventState(SDL_ENABLE);

        for(i=0;i<SDL_NumJoysticks();i++) {
            joy[i]=SDL_JoystickOpen(i);

            //Check for valid joystick, some keyboards
            //aren't SDL compatible
            if(joy[i])
            {
                if (SDL_JoystickNumAxes(joy[i]) > 28)
                {
                    SDL_JoystickClose(joy[i]);
                    joy[i]=0;
                    logoutput("Error detected invalid joystick/keyboard\n");
                }
                else
                    joyCount++;
            }
        }
        if(joy[0])
            logoutput("Found %d joysticks\n",joyCount);
    }
    else
        joyCount=1;
```

As we can see in the [last else](https://github.com/RetroPie/pifba/blob/master/rpi/gp2xsdk.cpp#L285), if no joysticks found, joyCount receives 1.

In other words: "If no joysticks found, let's pretend that we have one for player1 (and let's see if fba2x.cfg has some configs to control player1 with a keyboard)."

The problem is that in this scenario (no joysticks), there is no way to control player2, even if the user has a properly configured fba2x.cfg to control player2 with the same keyboard as the player1.

If we replace the [line 286](https://github.com/RetroPie/pifba/blob/master/rpi/gp2xsdk.cpp#L286) with `joyCount=2;`, pifba will understand that there is a minimum of 2 players.

In other words: "If no joysticks found, let's pretend that we have two, for player1 and player2 (and let's see if fba2x.cfg has some configs to control player1 and player2 with a keyboard)."

I've made a PR to fix it #5, worked really fine for me.

**Comment by dergrunepunkt** [comment]
I'm having this problem as well, please fix it!!!

**Comment by meleu** [comment]
It's already fixed. This issue can be closed.

**Comment by dergrunepunkt** [comment]
I'm testing a MAME controller based on a Arudino Leonardo that emulates a keyboard on Retropie with the lastest version compiled from source and the problem seems to fixed but not on theirs package version!.
Thanks a lot for this great piece of software!

**Comment by meleu** [comment]
@dergrunepunkt you're right. I've just "updated" from binary now and see that it was compiled in 20-Jul-2016. And my last PR ( #7 ) related with this issue was in 31-Jul-2016.
Maybe @joolswills can solve it for the next RetroPie release.
